<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Homepage extends Model
{
    protected $fillable = [
        'name',
        'hero_title',
        'hero_subtitle',
        'trust_strip',
        'ticker_label',
        'ticker_items',
        'rideon_image',
        'rideon_heading',
        'rideon_paragraph_1',
        'rideon_paragraph_2',
        'rideon_bullets',
        'rideon_cta_text',
        'rideon_cta_link',
        'services_eyebrow',
        'services_heading',
        'services_subheading',
        'services',
        'fleet_eyebrow',
        'fleet_heading',
        'fleet_subheading',
        'fleet_vehicles',
        'why_eyebrow',
        'why_heading',
        'why_features',
        'why_rating_value',
        'why_rating_description',
        'why_mini_stats',
        'highlight_icon',
        'highlight_heading',
        'highlight_description',
        'highlight_mini_boxes',
        'highlight_section_title',
        'highlight_section_text',
        'highlight_feature_list',
        'highlight_cta_text',
        'highlight_cta_link',
        'highlight_about_heading',
        'highlight_about_text',
        'testimonials_eyebrow',
        'testimonials_heading',
        'testimonials_subheading',
        'testimonials',
        'faq_eyebrow',
        'faq_heading',
        'faq_subheading',
        'faqs',
        'contact_eyebrow',
        'contact_heading',
        'contact_description',
        'contact_email',
        'contact_location',
        'sections_enabled',
        'cta_heading',
        'cta_description',
        'cta_primary_button_text',
        'cta_primary_button_link',
        'cta_secondary_button_text',
        'cta_secondary_button_link',

        'seo_title',
        'seo_description',
        'seo_meta_keywords',
        'seo_schema_markup'
    ];

    protected $casts = [
        'trust_strip' => 'array',
        'ticker_items' => 'array',
        'rideon_bullets' => 'array',
        'services' => 'array',
        'fleet_vehicles' => 'array',
        'why_features' => 'array',
        'why_mini_stats' => 'array',
        'highlight_mini_boxes' => 'array',
        'highlight_feature_list' => 'array',
        'testimonials' => 'array',
        'faqs' => 'array',
        'sections_enabled' => 'array',
    ];
}
