<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pages extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'hero_badge_text',
        'hero_title_line1',
        'hero_title_line2',
        'hero_title_gradient_text',
        'hero_description',
        'hero_background_image',
        'hero_benefits',
        'hero_form_discount_text',
        'hero_form_submit_text',
        'hero_form_note_text',
        'stats',
        'services_label',
        'services_heading_line1',
        'services_heading_line2',
        'services_heading_gradient',
        'services_description',
        'services_button_text',
        'services_list',
        'about_badge',
        'about_heading_line1',
        'about_heading_line2',
        'about_description',
        'about_experience_years',
        'about_experience_text',
        'about_image',
        'about_checkmarks',
        'about_button_text',
        'about_button_link',
        'airports_label',
        'airports_heading_line1',
        'airports_heading_line2',
        'airports_view_all_text',
        'airports_list',
        'coverage_label',
        'coverage_heading_line1',
        'coverage_heading_line2',
        'coverage_description',
        'coverage_button_text',
        'coverage_map_image',
        'coverage_background_image',
        'coverage_float_card_title',
        'coverage_float_card_route',
        'coverage_float_card_price',
        'coverage_float_card_price_text',
        'fleet_label',
        'fleet_heading',
        'fleet_subheading',
        'fleet_view_all_text',
        'story_label',
        'story_heading_line1',
        'story_heading_line2',
        'story_paragraph1',
        'story_paragraph2',
        'story_image',
        'story_values',
        'reviews_label',
        'reviews_heading',
        'reviews_description',
        'reviews_enabled',
        'reviews_list',
        'faq_label',
        'faq_heading',
        'faq_description',
        'faq_enabled',
        'faq_list',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'meta_og_image',
        'schema_enabled',
        'schema_type',
        'schema_org_name',
        'schema_org_url',
        'schema_org_logo',
        'schema_org_phone',
        'schema_org_email',
        'schema_business_street',
        'schema_business_city',
        'schema_business_state',
        'schema_business_postal',
        'schema_business_country',
        'schema_social_profiles',
        'schema_custom_json',
        'hero_title',

        'hero_subtitle',
        'trust_strip',
        'ticker_label',
        'ticker_items',
        'rideon_image',
        'rideon_heading',
        'rideon_paragraph_1',
        'rideon_paragraph_2',
        'rideon_bullets',
        'rideon_cta_text',
        'rideon_cta_link',
        'services_eyebrow',
        'services_heading',
        'services_subheading',
        'services',
        'fleet_eyebrow',
        'fleet_heading',
        'fleet_subheading',
        'fleet_vehicles',
        'why_eyebrow',
        'why_heading',
        'why_features',
        'why_rating_value',
        'why_rating_description',
        'why_mini_stats',
        'highlight_icon',
        'highlight_heading',
        'highlight_description',
        'highlight_mini_boxes',
        'highlight_section_title',
        'highlight_section_text',
        'highlight_feature_list',
        'highlight_cta_text',
        'highlight_cta_link',
        'highlight_about_heading',
        'highlight_about_text',
        'testimonials_eyebrow',
        'testimonials_heading',
        'testimonials_subheading',
        'testimonials',
        'faq_eyebrow',
        'faq_heading',
        'faq_subheading',
        'faqs',
        'contact_eyebrow',
        'contact_heading',
        'contact_description',
        'contact_email',
        'contact_location',
        'sections_enabled',

        'cta_heading',
        'cta_description',
        'cta_primary_button_text',
        'cta_primary_button_link',
        'cta_secondary_button_text',
        'cta_secondary_button_link',

        'seo_title',
        'seo_description',
        'seo_meta_keywords',
        'seo_schema_markup'
    ];

    protected $casts = [
        'hero_benefits' => 'array',
        'stats' => 'array',
        'services_list' => 'array',
        'about_checkmarks' => 'array',
        'airports_list' => 'array',
        'fleet_vehicles' => 'array',
        'story_values' => 'array',
        'reviews_list' => 'array',
        'faq_list' => 'array',
        'sections_enabled' => 'array',
        'reviews_enabled' => 'boolean',
        'faq_enabled' => 'boolean',
        'schema_enabled' => 'boolean',
        'trust_strip' => 'array',
        'ticker_items' => 'array',
        'rideon_bullets' => 'array',
        'services' => 'array',
        'fleet_vehicles' => 'array',
        'why_features' => 'array',
        'why_mini_stats' => 'array',
        'highlight_mini_boxes' => 'array',
        'highlight_feature_list' => 'array',
        'testimonials' => 'array',
        'faqs' => 'array',
    ];
}
