<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WebsiteSetting extends Model
{
    use HasFactory;

    protected $table = 'website_settings';

    protected $fillable = [
        'hero_badge_text',
        'hero_title_line1',
        'hero_title_line2',
        'hero_title_gradient_text',
        'hero_description',
        'hero_background_image',
        'hero_benefits',
        'hero_form_discount_text',
        'hero_form_submit_text',
        'hero_form_note_text',
        'stats',
        'services_label',
        'services_heading_line1',
        'services_heading_line2',
        'services_heading_gradient',
        'services_description',
        'services_button_text',
        'services_list',
        'about_badge',
        'about_heading_line1',
        'about_heading_line2',
        'about_description',
        'about_experience_years',
        'about_experience_text',
        'about_image',
        'about_checkmarks',
        'about_button_text',
        'about_button_link',
        'airports_label',
        'airports_heading_line1',
        'airports_heading_line2',
        'airports_view_all_text',
        'airports_list',
        'coverage_label',
        'coverage_heading_line1',
        'coverage_heading_line2',
        'coverage_description',
        'coverage_button_text',
        'coverage_map_image',
        'coverage_background_image',
        'coverage_float_card_title',
        'coverage_float_card_route',
        'coverage_float_card_price',
        'coverage_float_card_price_text',
        'fleet_label',
        'fleet_heading',
        'fleet_subheading',
        'fleet_view_all_text',
        'fleet_vehicles',
        'story_label',
        'story_heading_line1',
        'story_heading_line2',
        'story_paragraph1',
        'story_paragraph2',
        'story_image',
        'story_values',
        'reviews_label',
        'reviews_heading',
        'reviews_description',
        'reviews_enabled',
        'reviews_list',
        'faq_label',
        'faq_heading',
        'faq_description',
        'faq_enabled',
        'faq_list',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'meta_og_image',
        'sections_enabled',
        'schema_enabled',
        'schema_type',
        'schema_org_name',
        'schema_org_url',
        'schema_org_logo',
        'schema_org_phone',
        'schema_org_email',
        'schema_business_street',
        'schema_business_city',
        'schema_business_state',
        'schema_business_postal',
        'schema_business_country',
        'schema_social_profiles',
        'schema_custom_json',
    ];

    protected $casts = [
        'hero_benefits' => 'array',
        'stats' => 'array',
        'services_list' => 'array',
        'about_checkmarks' => 'array',
        'airports_list' => 'array',
        'fleet_vehicles' => 'array',
        'story_values' => 'array',
        'reviews_list' => 'array',
        'faq_list' => 'array',
        'sections_enabled' => 'array',
        'reviews_enabled' => 'boolean',
        'faq_enabled' => 'boolean',
        'schema_enabled' => 'boolean',
    ];
}
